name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        script: |
          cd /var/www
          rm -rf careertech-temp
          git clone https://github.com/Ceebl/Careertech.git careertech-temp
          
          # Deploy Project1
          sudo rsync -av --delete /var/www/careertech-temp/Project1/ /var/www/project1/
          sudo chown -R www-data:www-data /var/www/project1
          
          # Deploy Project2
          sudo rsync -av --delete /var/www/careertech-temp/Project2/ /var/www/project2
          sudo chown -R www-data:www-data /var/www/project2
          
          rm -rf /var/www/careertech-temp
